### ISSUE TITLE
Not able to turn off email in standard checks

### ISSUE THREAD

**Issue by leifg** [ianheggie/health_check#16]
Hello, we would like to be able to turn off "email" in the standard checks but by looking at the code this is not possible.

See [here](https://github.com/ianheggie/health_check/blob/master/lib/health_check/utils.rb#L50) the email check will always be added to standard check no matter how it is overwritten.

**Comment by pangkalizer** [comment]
+1

**Comment by cconstantine** [comment]
+1

**Comment by kenton** [comment]
+1

We needed this turned off for all checks for a project I'm working on.  The workaround we used until this is fixed is to include something like this in the health_check.rb initializer:

```ruby
HealthCheck::Utils.default_smtp_settings = ActionMailer::Base.smtp_settings
```

which makes the conditional here return `false`:
https://github.com/ianheggie/health_check/blob/master/lib/health_check/utils.rb#L50

that conditional is defined here:
https://github.com/ianheggie/health_check/blob/master/lib/health_check/utils.rb#L75

**Comment by hpoydar** [comment]
+1
