### ISSUE TITLE
Question: How may I silence the log output from the health check

### ISSUE THREAD

**Issue by Piioo** [ianheggie/health_check#18]
Our load balancer is checking every 2 sec if the server is alive and the logfile is filled with this requests.

Is there an option to do this?

**Comment by ianheggie** [comment]
I have not found a simple reliable way of doing it in recent versions of rails, so no, there is not an options. If you find one, I can incorporate it into the gem.

**Comment by leifg** [comment]
There are plenty of ways.

Most of them need additional gems though. We use [lograge](https://github.com/roidrage/lograge) for logging and it ships with a silencer.

Just use:

    config.lograge.ignore_actions = ["health_check/health_check#index"]

to silence all health checks.

A more simple approach is to use the [silencer gem](https://github.com/stve/silencer)

**Comment by Piioo** [comment]
Thx, the lograge is nice. 
silencer was to old for my feelings :)

**Comment by ianheggie** [comment]
Released in v2.0.0: Added comment to README
