### ISSUE TITLE
Version bump to 1.5.2 and deploy to rubygems?

### ISSUE THREAD

**Issue by leonardteo** [ianheggie/health_check#24]
Hi,

Is Master stable enough to do a version bump and deploy to rubygems?

This commit is actually quite significant and only exists on master right now:
https://github.com/ianheggie/health_check/commit/65f4126ce6188efb1dac6af05adef58708ff81e2

If you are using an external mail provider such as Mandrill, the extra time it takes to do the SMTP check can cause a load balancer fail a health check. There are workarounds to the issue but it would be good to do a release if it's stable enough.

Thanks!

Leo

**Comment by twk3** [comment]
@ianheggie I also would like the version bumped for this commit. There seems to be some smtp configs that don't quite work with the check, and we would like to exclude the check from the standard checks for now:

https://gitlab.com/gitlab-org/gitlab-ce/issues/17742

**Comment by ianheggie** [comment]
Fixed in v2.0.0
