### ISSUE TITLE
Allow setting of parent controller

### ISSUE THREAD

**Issue by twk3** [ianheggie/health_check#28]
It would be nice to have the option of setting the parent controller, similar to devise: https://github.com/plataformatec/devise/blob/0c1b1a896f549f92d76baf06fcece150420e94bf/lib/devise.rb#L222

In my use case I am extending your controller with my own in order to add some before action checks, and it would have been ideal to have had my own ApplicationController in the mix.

**Comment by ianheggie** [comment]
I don't want settings to depend on class loading/execution order - instead consider refactoring out the common code into a module and mix that into both your application controller and the sub classed healthcheck controller.
