### ISSUE TITLE
Naming custom health checks

### ISSUE THREAD

**Issue by vergenzt** [ianheggie/health_check#42]
It'd be nice if custom health checks could be given names so that e.g. `/health_check/my_custom_check.json` and `/health_check/my_other_custom_check.json` could be separated.

Any thoughts?

**Comment by ianheggie** [comment]
I'd happily accept a pull request for this feature, with (working) tests, but it isn't an itch I personally feel the need to scratch.

**Comment by ianheggie** [comment]
Do you want to do a pull request for this feature?

**Comment by ianheggie** [comment]
Added into v2.6.0

**Comment by vergenzt** [comment]
Thanks! Excited to try this out.
