### ISSUE TITLE
Discussion on without DB middleware

### ISSUE THREAD

**Issue by wyaeld** [ianheggie/health_check#43]
@ianheggie 

There is an interesting post here
https://thisdata.com/blog/making-a-rails-health-check-that-doesnt-hit-the-database/

They discuss the approach of using a specific stage in the middleware cycle to have a healthcheck that doesn't hit the DB, since the `QueryCache` middleware will hit the DB even if you don't include db checks in your healthcheck config.

I wanted to know if you think including something like that as an option is a useful addition to this gem?

**Comment by ianheggie** [comment]
PR #46 "Health check as middleware" has just been included in v2.3.0 (for rails 4.0 onwards) - this allows you to exclude the DB check. (Thanks @filiphaftek)

**Comment by wyaeld** [comment]
excellent work guys, thankyou
