### ISSUE TITLE
Deprecation warning with Rails 5

### ISSUE THREAD

**Issue by nwlucas** [ianheggie/health_check#44]
**DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.**

After constantly seeing that warning for days, I finally tracked it down to this gem. I forked it and changed the one place I saw it. Warning have since cleared.

The modification made was in `lib\health_check\health_check_controller.rb` 
from:
```ruby
module HealthCheck
  class HealthCheckController < ActionController::Base

    layout false if self.respond_to? :layout
    before_filter :authenticate
```
to:
```ruby
module HealthCheck
  class HealthCheckController < ActionController::Base

    layout false if self.respond_to? :layout
    before_action :authenticate
```

**Comment by ianheggie** [comment]
That commit has one test failing, when it is fixed I can merge it.
