### ISSUE TITLE
S3 check should not assume configuration in Rails secrets file

### ISSUE THREAD

**Issue by hotgazpacho** [ianheggie/health_check#62]
The `S3HealthCheck` class makes a couple of assumptions that are not always true:
1. The AWS configuration will reside in `Rails.application.secrets`
2. That configuration must be provided

These are two heavy assumptions to make. Instead, this module should allow the `aws-sdk` gem to divine the configuration from the environment, either from the `AWS_XXX` environment variables, or the EC2 instance profile _(when available)_. See the [SDK documentation on configuration](https://github.com/aws/aws-sdk-ruby#configuration)

**Comment by ianheggie** [comment]
I agree, in fact would go a bit further and say that you should be able to optionally pass configuration information into this check. Would you like to re-factor the code and submit a PR?

For the configuration, I think having config.options start as an empty hash, to be configured in the initializer and then tests check options['test-name'] for options they care about. This would fit in well with some other requests, and allow the original author of the S3 check to just add the following in an initializer:

    config.options['s3'] = aws_configuration = aws_configuration = {
          region: Rails.application.secrets.aws_default_region,
          credentials: ::Aws::Credentials.new(
            Rails.application.secrets.aws_access_key_id,
            Rails.application.secrets.aws_secret_access_key
          ),
          force_path_style: true
    }

**Comment by MrOutis** [comment]
is someone working on this? @ianheggie, @hotgazpacho

**Comment by ianheggie** [comment]
@hotgazpacho, @MrOutis - I haven’t had time to work on this. Anyone willing to submit a PR?

**Comment by MrOutis** [comment]
I'm willing to take the bullet during the weekend, @ianheggie

**Comment by ianheggie** [comment]
As much as possible, please do the write test, see it fail, write the code, see it pass style. If that’s not practical then if you keep tests in separate commits then afterwards you can do a fresh branch off master, cherry pick the tests into it, confirm they all fail because you havn't brought the code across, then cherry pick the code, check it all works then discard the original branch. (I find the gitk --all command very useful with its right click cherry picking) - THANKS FOR WORKING ON THE PR!!

**Comment by MrOutis** [comment]
I'll, @ianheggie, thanks for your advice

**Comment by ianheggie** [comment]
How are you going with this @mroutis ?? I am guessing you are as flat chat as I am on other things.

**Comment by natefaerber** [comment]
@mroutis and @ianheggie , https://github.com/ianheggie/health_check/pull/77 will take care of this.

**Comment by shlima** [comment]
@hotgazpacho you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
Fixed via PR that has been merged, new version will be release shortly

**Comment by ianheggie** [comment]
Provided in version 3.1.0 released just now
