### ISSUE TITLE
Different host for Redis

### ISSUE THREAD

**Issue by Eliada** [ianheggie/health_check#63]
Hi,

RedisHealthCheck is always failing because my redis is in another host, and the test only checks the default host: `127.0.0.1`. Is there a way to set a redis host to HealthCheck?

Thanks

**Comment by ianheggie** [comment]
Not currently, but I put a comment on #62 about implementing a config.options so options could be passed to tests. Do you want to submit a PR with this change?

**Comment by archana-juvo** [comment]
I've opened a pull request for this issue https://github.com/ianheggie/health_check/pull/65

**Comment by ianheggie** [comment]
Thanks @archana-juvo! - I have merged that PR.
