### ISSUE TITLE
No such middleware to insert after: "Rails::Rack::Logger"

### ISSUE THREAD

**Issue by ndbroadbent** [ianheggie/health_check#66]
I got this error when adding the following line to `config/application.rb`:

```ruby
config.middleware.insert_after "Rails::Rack::Logger", HealthCheck::MiddlewareHealthcheck
```

I'm using Rails 5.1.4. I ran `rake middleware` and can see: `use Rails::Rack::Logger`.

I think the syntax changed, and strings are no longer supported. This worked though:

```ruby
config.middleware.insert_after Rails::Rack::Logger, HealthCheck::MiddlewareHealthcheck
```

**Comment by ianheggie** [comment]
I have added the fix_middleware_insert_after branch with a rails51 gemfile, but there are obviously other issues with the test.

**Comment by ianheggie** [comment]
Thanks to your input - I have resolved the other issues and have incorporated your fix manually.
