### ISSUE TITLE
Issue installing in 5.1.5.rc1

### ISSUE THREAD

**Issue by illegalnumbers** [ianheggie/health_check#73]
I get the following error when trying to install health_check with Rails 5.1.5.rc1.

I think this is an error in health_check but I am not sure and would like some help debugging.

`Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    health_check (~> 1.5) was resolved to 1.5.0, which depends on
      rails (>= 2.3.0) was resolved to 2.3.2, which depends on
        actionpack (= 2.3.2)

    railties (~> 5.1.5.rc1) was resolved to 5.1.5.rc1, which depends on
      actionpack (= 5.1.5.rc1)`

**Comment by ianheggie** [comment]
I have (hopefully) clarified gem versions in the new README as part of the my reorganization of branches:
Use gem versions for stable releases, or github branch / commits for development versions:

    gem versions ~> 3.0 for Rails 5.x, or the rails5 development branch

    gem versions ~> 2.0 for Rails 4.x, or the rails4 development branch;

    gem versions ~> 1.7 for Rails 3.x, or the rails3 development branch;

    gem versions ~> 1.6.1 for Rails 2.3, or the rails2.3 development branch;

    master branch for edge development;

I am updating all the branches and am checking for ruby and gem version incompatibilities, so if it is still a problem in a weeks time, please let me know.

**Comment by ianheggie** [comment]
Update your Gemfile line to `gem "health_check", '~>3.0'` and that should fix your problem (version 1.5.2 was for rails 2.3) - Also Rails 5.1.5 has been released, so update that line as well.
