### ISSUE TITLE
Issues with custom checks

### ISSUE THREAD

**Issue by DannyBen** [ianheggie/health_check#79]
I am having some more issues with the custom events configuration. It feels like they are not a first class citizen in this gem, which is a shame.

In addition to issue #78 that I opened, I am also facing this one:

When adding more than one custom checks, in case they are both failing, the output string is not properly formatted.

```ruby
config.add_custom_check('events') { "this has failed" }
config.add_custom_check('scheduler') { "this has also failed" }
```

When both checks fail, I am getting both messages like this:

```
health_check failed: this has failedthis has also failed
```

Problems with this message:

1. There is no separation between messages, of any kind.
2. There is no mention of which of the tests has failed, eventhough this information was provided as the custom check name.

I expected to get something like this as output:

```
health_check failed:
- events: this has failed
- scheduler: this has also failed
```

I am not sure if regular events behave the same, but if so, I hope it can be fixed to properly report on multiple failures.

**Comment by ianheggie** [comment]
Errors will be listed with comma separations in next release (soon)

**Comment by DannyBen** [comment]
Thank you.
