### ISSUE TITLE
Redis health check keeps connections open

### ISSUE THREAD

**Issue by DannyBen** [ianheggie/health_check#80]
I have seen my Redis connection count skyrocket due to the fact that the redis health check assigns a new `Redis` instance on each call:

https://github.com/ianheggie/health_check/blob/e72703c088e7d52d781b52ae01a75d68a5786feb/lib/health_check/redis_health_check.rb#L6-L10

Maybe it would make sense to allow us to set a `HealthCheck.redis_client` instead of `HealthCheck.redis_url` ? This way, I can do `HealthCheck.redis_client = $redis`, or whatever logic I have to maintain a single client or a pool of clients.

If not that, then maybe call `res.disconnect!` when done?

**Comment by cobyrne09** [comment]
This gem looks great, and I really want to implement it at company, but do changes only get merged once a year after new rails releases?

**Comment by shlima** [comment]
@DannyBen @cobyrne09 you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
@DannyBen @cobyrne09 - PR that fixes issue has been merged and after I have finished testing the PRs I have merged I will release shortly

**Comment by DannyBen** [comment]
Thanks - but I moved on to my own custom solution long ago. Feel free to close this issue.

**Comment by ianheggie** [comment]
Done, (And Fix is in version 3.1.0 released just now for anyone else that is curious)
