### ISSUE TITLE
Merge default SMTP settings?

### ISSUE THREAD

**Issue by benlinton** [ianheggie/health_check#82]
Should SMTP defaults:
https://github.com/ianheggie/health_check/blob/master/lib/health_check/utils.rb#L7

Get reverse merged in here?
https://github.com/ianheggie/health_check/blob/master/lib/health_check/utils.rb#L122

**Comment by shlima** [comment]
@benlinton you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
No, the default smtp settings are just there to detect if the current settings match the default or have been changed, in which case checking of smtp is enabled. They should not be merged, the actual settings are what should be used to check.
