### ISSUE TITLE
Make v.4 release

### ISSUE THREAD

**Issue by shlima** [ianheggie/health_check#86]
Please release v.4 version

**Comment by joekimmel** [comment]
@ianheggie   Thanks for this gem -- any chance of updating the release just with exactly the features already in master?

**Comment by shlima** [comment]
@joekimmel you can check an [alternative](https://github.com/shlima/health_bit)

**Comment by ianheggie** [comment]
Happening soon

**Comment by ianheggie** [comment]
Rails 5 and 6 support in version 3.1.0 released just now - includes further enhancements and passes tests
