### ISSUE TITLE
Add Functionality to add new relic APM to ignore health_check route

### ISSUE THREAD

**Issue by rahil-helios** [ianheggie/health_check#95]

**Comment by wacaw** [comment]
> New Relic for Ruby allows you to selectively disable instrumentation for particular requests within your Rails or Sinatra application. [...]
>  You can ignore transactions by URL using the rules.ignore_url_regexes configuration setting: 

https://docs.newrelic.com/docs/agents/ruby-agent/api-guides/ignoring-specific-transactions

**Comment by ianheggie** [comment]
Thanks wacaw, I think that's the best solution
