### ISSUE TITLE
Adding handler in case of failure

### ISSUE THREAD

**Issue by mithucste30** [ianheggie/health_check#99]
Hi i am already using exception notification gem for sending exceptions from the app. Can I add that email sending block to to this gem in case when the health check fails?

**Comment by ianheggie** [comment]
Sounds a good idea, do you want to submit a Pull request with the suggested change?

**Comment by ianheggie** [comment]
I am in the process of adding on_failure and on_success callbacks

**Comment by ianheggie** [comment]
Provided in version 3.1.0 released just now
